Migration 3.0
veliovgroup/flow-router pull request #113
Opened 2024-07-25 16:13 UTC by TheRuggster

Thank you for contribution. Before you go:
  1. Make sure you're using `spaces` for indentation
  2. Make sure all new code is documented in-code-docs
  3. Make sure new features, or changes in behavior is documented in README.md and/or other docs materials
  4. Make sure this PR was previously discussed, if not create new issue ticket for your PR
  5. Give an expressive description what you have changed/added and why
  
Thank you for making this package better :)

## Do not forget to get rid of this default message

2024-07-25 16:15 UTC, TheRuggster commented
updated with original version

2024-07-25 17:01 UTC, dr-dimitru commented
@TheRuggster what was changed?

2024-07-26 07:08 UTC, TheRuggster commented
@dr-dimitru sorry it was a mistake. you can close

2024-07-26 07:10 UTC, dr-dimitru commented
@TheRuggster does it work well on 3.0 for you?

2024-07-27 12:22 UTC, dr-dimitru commented
@TheRuggster ? 🤔

2024-07-29 09:39 UTC, jankapunkt requested changes

2024-07-29 09:39 UTC, jankapunkt commented on package.js
> +  api.versionsFrom(['3.0']);
THis should be 

```js
api.versionsFrom(['1.4', '2.8.0', '3.0.1']);
```

for best compatibility

2024-07-29 09:39 UTC, jankapunkt commented on package.js
>    api.use(['zodern:types@1.0.13', 'typescript'], ['client', 'server'], { weak: true });
In the line below this one (now shown in this diff) you need to support Blaze 2 and 3:

```js
  api.use(['templating', 'blaze@2.0.0 || 3.0.0'], 'client', { weak: true });
```

2024-07-29 12:23 UTC, TheRuggster commented
@jankapunkt suggestions added

2024-07-29 12:38 UTC, jankapunkt approved these changes

2024-07-29 12:39 UTC, jankapunkt commented
@dr-dimitru lgtm

2024-11-11 14:39 UTC, ferjep commented
Any updates on this merge?

2024-12-19 12:55 UTC, harryadel commented
Ping @dr-dimitru

2025-01-25 21:34 UTC, dr-dimitru approved these changes

2025-01-26 19:30 UTC, dr-dimitru commented
@TheRuggster I wasn't able to merge this PR due to conflicts, so I applied changes from this PR to `3.11.0` and mentioned you as contributor

2025-01-26 19:30 UTC, closed without merging